### ISSUE TITLE
Leap Year Consideration

### ISSUE THREAD

**Issue by jacksonbrumbaugh** [andrewhoyer/year-remaining#2]
Only skimmed the top like ~10 lines of generate.py

But have u considered what will happen for next year's Leap Year?

That does create the possible [0, 365] range for ur 1 variable (forgot the name specifically)

But then ur check if ( var >= 364 ) would behavior less than desired Dec 31, 2024 ... i ... think ...

**Comment by andrewhoyer** [comment]
The script has been updated to automatically determine the number of days in the year, rather than relying on a fixed value.

**Comment by andrewhoyer** [comment]
The script has been updated to automatically determine the number of days in the year, rather than relying on a fixed value.
